version: '3.9'

services:
  postgres:
    container_name: nest-001-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_js_001  # service attaches to this network

volumes:
  postgres_data:

networks:
  nest_js_001:    # define the network here as a mapping
